Models/ViewModels/ManageUserRolesViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BugTracker.Models.ViewModels
{
    public class ManageUserRolesViewModel
    {
        public BTUser BTUser { get; set; }
        public MultiSelectList Roles { get; set; }
        public List<string> SelectedRoles { get; set; }
    }
}

Controllers/UserRolesController.cs
#region USING STATEMENTS
using BugTracker.Extensions;
using BugTracker.Models;
using BugTracker.Models.ViewModels;
using BugTracker.Services.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks; 
#endregion

namespace BugTracker.Controllers
{
    [Authorize]
    public class UserRolesController : Controller
    {
        #region PRIVATE VARIABLES
        private readonly IBTRolesService _rolesService;
        private readonly IBTCompanyInfoService _companyInfoService;
        #endregion

        #region CONSTRUCTOR
        public UserRolesController(IBTRolesService rolesService, IBTCompanyInfoService companyInfoService)
        {
            _rolesService = rolesService;
            _companyInfoService = companyInfoService;
        }
        #endregion

        #region MANAGE USER ROLES
        #region GET
        [HttpGet]
        public async Task<IActionResult> ManageUserRoles()
        {
            //ADD AN INSTANCE OF THE VIEWMODEL AS A LIST
            List<ManageUserRolesViewModel> model = new();

            //GET CompanyId
            int companyId = User.Identity.GetCompanyId().Value;

            //GET ALL COMPANY USERS
            List<BTUser> companyUsersList = await _companyInfoService.GetAllMembersAsync(companyId);

            //LOOP OVER USERS TO POPULATE ViewModel
            foreach (BTUser user in companyUsersList)
            {
                ManageUserRolesViewModel viewModel = new();
                viewModel.BTUser = user;

                IEnumerable<string> selectedRoles = await _rolesService.GetUserRolesAsync(user);

                viewModel.Roles = new MultiSelectList(await _rolesService.GetRolesAsync(), "Name", "Name", selectedRoles);

                model.Add(viewModel);
            }

            return View(model);
        }
        #endregion



        #region POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ManageUserRoles(ManageUserRolesViewModel member)
        {
            //GET CompanyId
            int companyId = User.Identity.GetCompanyId().Value;

            //INSTANTIATE THE BTUSER
            BTUser btUser = (await _companyInfoService.GetAllMembersAsync(companyId)).FirstOrDefault(u => u.Id == member.BTUser.Id);

            //GET ROLES FOR THE USER
            IEnumerable<string> roles = await _rolesService.GetUserRolesAsync(btUser);

            //GRAB THE SELECTED ROLE
            string userRole = member.SelectedRoles.FirstOrDefault();

            if (!string.IsNullOrEmpty(userRole))
            {
                //REMOVE USER FROM ROLE
                if (await _rolesService.RemoveUserFromRolesAsync(btUser, roles))
                {
                    //ADD USER TO THE NEW ROLE
                    await _rolesService.AddUserToRoleAsync(btUser, userRole);
                }
            }

            //NAVIGATE BACK TO VIEW
            return RedirectToAction(nameof(ManageUserRoles));
        }
        #endregion
        #endregion
    }
}

Views/UserRoles/ManageUserRoles.cshtml
@using BugTracker.Models.ViewModels
@using BugTracker.Services.Interfaces
@model IEnumerable<ManageUserRolesViewModel>

@inject IBTFileService FileService


@{
    List<ManageUserRolesViewModel> modelList = Model.ToList();
    modelList =  modelList.OrderByDescending(n => n.BTUser.FullName).ToList();
}


<div class="row ms-4 me-4">
    <h2 class=""><b>Manage Member Roles</b></h2>

    @foreach (var member in Model)
    {

        <div class="col-sm-12 col-md-6 ">
            <div class="card mb-2">
                <div class="card-body">
                    <p class="text-muted font-13 m-b-30">
                        This form displays the current roles assigned to the user: <strong class="text-info">@member.BTUser.FullName</strong>.
                        Use the dropdown to select the roles this user should be assigned.
                        Once roles are selected, click "Assign Roles" to submit the form.
                    </p>
                    <hr />
                    <form asp-action="ManageUserRoles" asp-controller="UserRoles" method=post>
                        <input type="hidden" asp-for="@member.BTUser.Id" />
                        <div class="row">
                            <div class="col-6">
                                <div class="form-group">
                                    <label asp-for="@member.Roles" class="custom-label">Roles for @member.BTUser.FullName</label>
                                    <select asp-for="@member.SelectedRoles" class="form-control" asp-items="@member.Roles" multiple>
                                    </select>
                                    <hr />
                                </div>
                                <div class="form-group">
                                    <input type="submit" value="Assign Role" class="btn btn-info" />
                                </div>
                            </div>
                            <div class="col-6">
                                @if (member.BTUser?.AvatarFileData != null)
                                {
                                    <img class="media-object" src="@FileService.ConvertByteArrayToFile(member.BTUser.AvatarFileData,member.BTUser.AvatarContentType)" />
                                }
                                else
                                {
                                    <img class="img-fluid" src="https://cdn.icon-icons.com/icons2/1378/PNG/512/avatardefault_92824.png" alt=""  />
                                }
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    }
</div>