Models/Project.cs
using Microsoft.AspNetCore.Http;

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BugTracker.Models
{
    public class Project
    {
        public int Id { get; set; }

        [DisplayName("Comapany")]
        public int? CompanyId { get; set; }


        [Required]
        [StringLength(50)]
        [DisplayName("Project Name")]
        public string Name { get; set; }


        [DisplayName("Description")]
        public string Description { get; set; }

        [DisplayName("Project Start Date")]
        [DataType(DataType.Date)]
        public DateTimeOffset StartDate { get; set; }

        [DisplayName("Project End Date")]
        [DataType(DataType.Date)]
        public DateTimeOffset EndDate { get; set; }

        [DisplayName("Priority")]
        public int? ProjectPriorityId { get; set; }

        [NotMapped]
        [DataType(DataType.Upload)]
        public IFormFile ImageFormFile { get; set; }

        [DisplayName("File Name")]
        public string ImageFileName { get; set; }

        public byte[] ImageFileData { get; set; }

        [DisplayName("File Extension")]
        public string ImageContentType { get; set; }

        [DisplayName("Archive")]
        public bool Archived { get; set; }

        //Navigation properties
        public virtual Company Company { get; set; }
        public virtual ProjectPriority ProjectPriority { get; set; }
        public virtual ICollection<BTUser> Members { get; set; } = new HashSet<BTUser>();
        public virtual ICollection<Ticket> Tickets { get; set; } = new HashSet<Ticket>();

    }
}

Models/ViewModels/AssignPMViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;

namespace BugTracker.Models.ViewModels
{
    public class AssignPMViewModel
    {
        #region PROPERTIES
        public Project Project { get; set; }
        public SelectList PMList { get; set; }
        public string PMID { get; set; } 
        #endregion
    }
}

Controllers/ProjectsController.cs
#region USING STATEMENTS
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BugTracker.Data;
using BugTracker.Models;
using BugTracker.Extensions;
using BugTracker.Models.ViewModels;
using BugTracker.Services.Interfaces;
using BugTracker.Models.Enums;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
#endregion

namespace BugTracker.Controllers
{
    [Authorize]
    public class ProjectsController : Controller
    {
        #region INJECTION VARIABLES
        private readonly IBTRolesService _rolesService;
        private readonly IBTLookUpService _lookUpService;
        private readonly IBTFileService _fileService;
        private readonly IBTProjectService _projectService;
        private readonly UserManager<BTUser> _userManager;
        private readonly IBTCompanyInfoService _companyInfoService;
        #endregion

        #region CONSTRUCTOR
        public ProjectsController(IBTRolesService rolesService,
                                  IBTLookUpService lookUpService,
                                  IBTFileService fileService,
                                  IBTProjectService projectService,
                                  UserManager<BTUser> userManager,
                                  IBTCompanyInfoService companyInfoService)
        {
            
            _rolesService = rolesService;
            _lookUpService = lookUpService;
            _fileService = fileService;
            _projectService = projectService;
            _userManager = userManager;
            _companyInfoService = companyInfoService;
        }
        #endregion

        #region MY PROJECTS
        public async Task<IActionResult> MyProjects()
        {
            string userId = _userManager.GetUserId(User);

            List<Project> projects = await _projectService.GetUserProjectsAsync(userId);

            return View(projects);
        }
        #endregion

        #region ALL PROJECTS
        public async Task<IActionResult> AllProjects()
        {
            List<Project> projects = new();

            int companyId = User.Identity.GetCompanyId().Value;

            if (User.IsInRole(nameof(Roles.Admin)) || User.IsInRole(nameof(Roles.ProjectManager)))
            {
                projects = await _companyInfoService.GetAllProjectsAsync(companyId);
            }
            else
            {
                projects = await _projectService.GetAllProjectsByCompanyAsync(companyId);
            }

            return View(projects);
        }
        #endregion

        #region ARCHIVED PROJECTS
        public async Task<IActionResult> ArchivedProjects()
        {
            int companyId = User.Identity.GetCompanyId().Value;

            List<Project> projects = await _projectService.GetArchivedProjectsByCompany(companyId);

            return View(projects);
        }
        #endregion

        #region UNASSIGNED PROJECTS
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> UnassignedProjects()
        {
            int companyId = User.Identity.GetCompanyId().Value;

            List<Project> projects = new();

            projects = await _projectService.GetUnassignedProjectsAsync(companyId);

            return View(projects);
        }
        #endregion

        #region ASSIGN PROJECT MANAGER
        #region GET
        [Authorize(Roles = "Admin")]
        [HttpGet]
        public async Task<IActionResult> AssignPM(int projectId)
        {
            int companyId = User.Identity.GetCompanyId().Value;

            AssignPMViewModel model = new();

            model.Project = await _projectService.GetProjectByIdAsync(projectId, companyId);
            model.PMList = new SelectList(await _rolesService.GetUsersInRoleAsync(nameof(Roles.ProjectManager), companyId), "Id", "FullName");

            return View(model);
        }
        #endregion

        #region POST
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AssignPM(AssignPMViewModel model)
        {
            if (!string.IsNullOrEmpty(model.PMID))
            {
                await _projectService.AddProjectManagerAsync(model.PMID, model.Project.Id);

                return RedirectToAction(nameof(Details), new { id = model.Project.Id });
            }

            return RedirectToAction(nameof(AssignPM), new { projectId = model.Project.Id });
        }
        #endregion
        #endregion

        #region ASSIGN MEMBERS
        #region GET
        [Authorize(Roles = "Admin, ProjectManager")]
        [HttpGet]
        public async Task<IActionResult> AssignMembers(int id)
        {
            ProjectMembersViewModel model = new();

            int companyId = User.Identity.GetCompanyId().Value;

            model.Project = await _projectService.GetProjectByIdAsync(id, companyId);

            List<BTUser> developers = await _rolesService.GetUsersInRoleAsync(nameof(Roles.Developer), companyId);
            List<BTUser> submitters = await _rolesService.GetUsersInRoleAsync(nameof(Roles.Submitter), companyId);

            List<BTUser> companyMembers = developers.Concat(submitters).ToList();

            List<string> projectMembers = model.Project.Members.Select(m => m.Id).ToList();

            model.Users = new MultiSelectList(companyMembers, "Id", "FullName", projectMembers);

            return View(model);

        }
        #endregion
        #region POST
        [Authorize(Roles = "Admin, ProjectManager")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AssignMembers(ProjectMembersViewModel model)
        {
            if(model.SelectedUsers != null)
            {
                List<string> memberIds = (await _projectService.GetAllProjectMembersExceptPMAsync(model.Project.Id)).Select(m => m.Id).ToList();

                //REMOVE CURRENT MEMBERS - DO THIS TO AVOID DUPLICATES IN THE LIST
                foreach (string member in memberIds)
                {
                    await _projectService.RemoveUserFromProjectAsync(member, model.Project.Id);
                }

                //ADD SELECTED MEMBERS
                foreach (string  member in model.SelectedUsers)
                {
                    await _projectService.AddUserToProjectAsync(member, model.Project.Id);
                }

                //GO TO PROJECT DETAILS
                return RedirectToAction(nameof(Details), new { id = model.Project.Id });
            }

            return RedirectToAction(nameof(AssignMembers), new { id = model.Project.Id });
        }
        #endregion
        #endregion

        #region DETAILS
        // GET: Projects/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            int companyId = User.Identity.GetCompanyId().Value;

            Project project = await _projectService.GetProjectByIdAsync(id.Value, companyId);

            if (project == null)
            {
                return NotFound();
            }

            return View(project);
        }
        #endregion

        #region CREATE

        #region GET
        // GET: Projects/Create
        [Authorize(Roles = "Admin, ProjectManager")]
        public async Task<IActionResult> Create()
        {
            int companyId = User.Identity.GetCompanyId().Value;

            //ADD ViewModel INSTANCE
            AddProjectWithPMViewModel model = new();

            //LOAD SelectList WITH DATA
            model.PMList = new SelectList(await _rolesService.GetUsersInRoleAsync(Roles.ProjectManager.ToString(), companyId), "Id", "FullName");
            model.PriorityList = new SelectList(await _lookUpService.GetProjectPrioritiesAsync(), "Id", "Name");


            return View(model);
        }
        #endregion

        #region POST
        // POST: Projects/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Admin, ProjectManager")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(AddProjectWithPMViewModel model)
        {
            if (model != null)
            {
                int companyId = User.Identity.GetCompanyId().Value;

                try
                {
                    if (model.Project.ImageFormFile != null)
                    {
                        model.Project.ImageFileData = await _fileService.ConvertFileToByArrayAsync(model.Project.ImageFormFile);
                        model.Project.ImageFileName = model.Project.ImageFormFile.FileName;
                        model.Project.ImageContentType = model.Project.ImageFormFile.ContentType;
                    }

                    model.Project.CompanyId = companyId;

                    await _projectService.AddNewProjectAsync(model.Project);

                    if (!string.IsNullOrEmpty(model.PmId))
                    {
                        await _projectService.AddProjectManagerAsync(model.PmId, model.Project.Id);
                    }
                    return RedirectToAction("Dashboard", "Home", new { User.Identity.GetCompanyId().Value });
                }
                catch (Exception)
                {

                    throw;
                }
            }
            return RedirectToAction("Create");
        }
        #endregion
        #endregion

        #region EDIT
        #region GET
        // GET: Projects/Edit/5
        [Authorize(Roles = "Admin, ProjectManager")]
        public async Task<IActionResult> Edit(int? id)
        {

Views/Projects/AllProjects.cshtml
@model IEnumerable<BugTracker.Models.Project>
@using BugTracker.Models.Enums
@using Microsoft.AspNetCore.Identity
@using BugTracker.Services.Interfaces

@inject UserManager<BTUser> UserManager
@inject IBTProjectService _projectService
@inject IBTFileService _imageService

@{
    ViewData["Title"] = "All Projects";
    BTUser btUser = await UserManager.GetUserAsync(User);
}

<div class="ms-4 me-4 ">
    <h1>All Projects</h1>

    @if (User.IsInRole(nameof(Roles.Admin)) || User.IsInRole(nameof(Roles.ProjectManager)))
    {
        <p>
            <a asp-action="Create" class="btn btn-primary ">Create New</a>
        </p>
    }

    <hr />
    <div class="row">
        @foreach (Project project in Model.OrderBy(p => p.Name))
        {
            <div class="col-sm-12 col-md-6 pt-2 pb-2">
                <div class="card" style="height:auto; width:auto">
                    <div class="card-body">
                        <h4 class="card-title">@project.Name</h4>
                        <p class="card-text">@project.Description</p>
                        <div class="row">
                            <div class="col">
                                <a asp-controller="Projects" asp-action="Details" asp-route-id="@project.Id" class="btn btn-primary">Details</a>

                                @{
                                    bool isProjectPM = (await _projectService.GetProjectManagerAsync(project.Id))?.Id == btUser.Id;


                                    if (User.IsInRole(nameof(Roles.Admin)) || isProjectPM)
                                    {
                                        <a class="btn btn-primary" asp-controller="Projects" asp-action="Edit" asp-route-id="@project.Id">Edit</a>
                                        @if (project.Archived)
                                        {
                                            <a class="btn btn-success" asp-action="Restore" asp-controller="Projects" asp-route-id="@project.Id">Restore</a>
                                        }
                                        else
                                        {
                                            <a class="btn btn-danger" asp-controller="Projects" asp-action="Archive" asp-route-id="@project.Id">Archive</a>
                                        }
                                    }
                                }
                            </div>
                        </div>
                    </div>
                    <div class="card-footer">   </div>
                </div>
            </div>
        }
    </div>
</div>

Views/Projects/Archive.cshtml
@model BugTracker.Models.Project
@inject BugTracker.Services.Interfaces.IBTFileService _imageService
@{
    ViewData["Title"] = "Archive";
}

<h1>Archive</h1>

<h3>Are you sure you want to archive this project?</h3>
<div>
    <h4>Project</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.StartDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.EndDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ImageFileName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ImageFileName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ImageFileData)
        </dt>
        <dd class="col-sm-10">
            @if (Model.ImageFileData != null)
            {
                <img style="width:60px;height:60px" src="@_imageService.ConvertByteArrayToFile(Model.ImageFileData, Model.ImageContentType)" />
            }
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ImageContentType)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ImageContentType)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Archived)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Archived)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Company)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Company.Id)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ProjectPriority)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ProjectPriority.Name)
        </dd>
    </dl>

    <form asp-action="Archive">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Archive" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Projects/ArchivedProjects.cshtml
@model IEnumerable<BugTracker.Models.Project>
@using BugTracker.Models.Enums
@using Microsoft.AspNetCore.Identity
@using BugTracker.Services.Interfaces

@inject UserManager<BTUser> UserManager
@inject IBTProjectService _projectService
@inject IBTFileService _imageService

@{
    ViewData["Title"] = "Archived Projects";
    BTUser btUser = await UserManager.GetUserAsync(User);
}

<div class="ms-4 me-4 ">
    <h1>Archived Projects</h1>

    <hr />
    <div class="row">
        @foreach (Project project in Model.OrderBy(p => p.Name))
        {
            <div class="col-sm-12 col-md-6 pt-2 pb-2">
                <div class="card" style="height:auto; width:auto">
                    <div class="card-body">
                        <h4 class="card-title">@project.Name</h4>
                        <p class="card-text">@project.Description</p>
                        <div class="row">
                            <div class="col">
                                <a asp-controller="Projects" asp-action="Details" asp-route-id="@project.Id" class="btn btn-primary">Details</a>

                                @{
                                    bool isProjectPM = (await _projectService.GetProjectManagerAsync(project.Id))?.Id == btUser.Id;


                                    if (User.IsInRole(nameof(Roles.Admin)) || isProjectPM)
                                    {
                                        <a class="btn btn-primary" asp-controller="Projects" asp-action="Edit" asp-route-id="@project.Id">Edit</a>
                                        @if (project.Archived)
                                        {
                                            <a class="btn btn-success" asp-action="Restore" asp-controller="Projects" asp-route-id="@project.Id">Restore</a>
                                        }
                                        else
                                        {
                                            <a class="btn btn-danger" asp-controller="Projects" asp-action="Archive" asp-route-id="@project.Id">Archive</a>
                                        }
                                    }
                                }
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        }
    </div>
</div>

Views/Projects/AssignMembers.cshtml
@model BugTracker.Models.ViewModels.ProjectMembersViewModel

<div class="container">
    <h2>Assign Members for</h2>
    <div class="row">
        <div class="col-md-6">
            <h3>@Model.Project.Name</h3>
            <div class="card">
                <div class="card-header">
                    <label asp-for="@Model.Users" class="control-label">Assign team members for Project</label>
                </div>
                <div class="card-body">
                    <form method="post" asp-action="AssignMembers" asp-controller="Projects">
                        <input hidden asp-for="@Model.Project.Id" />
                        <div class="col-12 mb-3">
                            <div class="form-group">
                                <select required asp-for="@Model.SelectedUsers" class="form-control" asp-items="@Model.Users" multiple="multiple"></select>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-lg-offset-2 col-lg-10">
                                <input type="submit" class="btn alert-primary" value="Assign Users" />
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <div>
        <a asp-action="Details" asp-controller="Projects" asp-route-id="@Model.Project.Id">Back to Details</a>
    </div>
</div>

Views/Projects/AssignPM.cshtml
@model BugTracker.Models.ViewModels.AssignPMViewModel

@{
    ViewData["Title"] = "Assign PM";
}

<h1>Project: @Model.Project.Name</h1>

<h4>Assign Project Manager</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post" asp-action="AssignPM" asp-controller="Projects">
            <input hidden asp-for="Project.Id" />
            <h2>@Model.Project.Name</h2>

            <p>@Model.Project.Description</p>

            <div class="form-group">
                <label class="control-label">Select Project Manager</label>
                <select asp-for="PMID" class="form-control" asp-items="@Model.PMList">
                    <option></option>
                </select>

                <input type="submit" value="Assign" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="UnassignedProjects">Back to List</a>
</div>

Views/Projects/Create.cshtml
@model BugTracker.Models.ViewModels.AddProjectWithPMViewModel
@using BugTracker.Models.Enums
@{
    ViewData["Title"] = "Create";
}


<div class="ps-4 pe-4 ">
    <h1>Create</h1>

    <h4>Project</h4>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Create" method="post" enctype="multipart/form-data">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Project.Name" class="control-label"></label>
                    <input asp-for="Project.Name" class="form-control" />
                    <span asp-validation-for="Project.Name" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Project.Description" class="control-label"></label>
                    <input asp-for="Project.Description" class="form-control" />
                    <span asp-validation-for="Project.Description" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Project.StartDate" class="control-label"></label>
                    <input asp-for="Project.StartDate" class="form-control" />
                    <span asp-validation-for="Project.StartDate" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Project.EndDate" class="control-label"></label>
                    <input asp-for="Project.EndDate" class="form-control" />
                    <span asp-validation-for="Project.EndDate" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label class="control-label">Choose a priority</label>
                    <select asp-for="Project.ProjectPriorityId" class="form-control" asp-items="@Model.PriorityList"></select>
                </div>
                @*Set up Image capture*@
                <div class="form-group">
                    <label class="control-label">Project Image</label>
                    <input asp-for="Project.ImageFormFile" class="form-control" type="file" accept=".png, .jpg,.jpeg,.gif"
                           onchange="document.getElementById('imageFileData').src = window.URL.createObjectURL(this.files[0])" />
                    <span asp-validation-for="Project.ImageFormFile" class="text-danger"></span>
                </div>
                <label>Image Preview</label>
                @if (Model.Project?.ImageFileData != null)
                {
                    <img id="imageFileData" class="img-fluid img-thumbnail" style="width:100px;height:80px;" src="data:image/*;base64,@(Convert.ToBase64String(Model.Project.ImageFileData))" />
                }
                else
                {
                    <img id="imageFileData" class="img-fluid img-thumbnail" style="width:100px;height:80px;" />

                }
                @*Fix up PM SelectList*@
                @if (User.IsInRole(Roles.Admin.ToString()))
                {
                    <div class="form-group">
                        <label class="control-label">Project Manager</label>
                        <select asp-for="PmId" class="form-control" asp-items="@Model.PMList">
                            <option></option>
                        </select>
                    </div>
                }
                <div class="form-group pt-2">
                    <input type="submit" value="Create" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>
    <!--
    <div class="pt-2">
        <a asp-action="Index" class="btn btn-primary ">Back to List</a>
    </div> --> 
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Projects/MyProjects.cshtml
@model IEnumerable<BugTracker.Models.Project>
@using BugTracker.Models.Enums
@using Microsoft.AspNetCore.Identity
@using BugTracker.Services.Interfaces

@inject UserManager<BTUser> UserManager
@inject IBTProjectService _projectService
@inject IBTFileService _imageService
@{
    ViewData["Title"] = "My Projects";
    BTUser btUser = await UserManager.GetUserAsync(User);

}

<div class="ms-4 me-4">
    <h1>My Projects</h1>
    @if (User.IsInRole(nameof(Roles.Admin)) || User.IsInRole(nameof(Roles.ProjectManager)))
    {
        <p>
            <a class="btn btn-primary" asp-action="Create">Create New</a>
        </p>
    }

    <hr />
    <div class="row">
        @foreach (Project project in Model.OrderBy(p => p.Name))
        {
            <div class="col-sm-12 col-md-6 pt-2 pb-2">
                <div class="card" style="height:auto; width:auto">
                    <div class="card-body">
                        <h4 class="card-title">@project.Name</h4>
                        <p class="card-text">@project.Description</p>
                        <div class="row">
                            <div class="col">
                                <a asp-controller="Projects" asp-action="Details" asp-route-id="@project.Id" class="btn btn-primary">Details</a>

                                @{
                                    bool isProjectPM = (await _projectService.GetProjectManagerAsync(project.Id))?.Id == btUser.Id;


                                    if (User.IsInRole(nameof(Roles.Admin)) || isProjectPM)
                                    {
                                        <a class="btn btn-primary" asp-controller="Projects" asp-action="Edit" asp-route-id="@project.Id">Edit</a>
                                        @if (project.Archived)
                                        {
                                            <a class="btn btn-success" asp-action="Restore" asp-controller="Projects" asp-route-id="@project.Id">Restore</a>
                                        }
                                        else
                                        {
                                            <a class="btn btn-danger" asp-controller="Projects" asp-action="Archive" asp-route-id="@project.Id">Archive</a>
                                        }
                                    }
                                }
                            </div>
                        </div>
                    </div>
                    <div class="card-footer">   </div>
                </div>
            </div>
        }
    </div>
</div>

Views/Projects/UnassignedProjects.cshtml
@model IEnumerable<BugTracker.Models.Project>
@using BugTracker.Models.Enums
@using Microsoft.AspNetCore.Identity
@using BugTracker.Services.Interfaces

@inject UserManager<BTUser> UserManager
@inject IBTProjectService _projectService
@inject IBTFileService _imageService

@{
    ViewData["Title"] = "Unassigned Projects";
    BTUser btUser = await UserManager.GetUserAsync(User);
}

<div class="ms-4 me-4 ">
    <h1>Unassigned Projects</h1>

    <hr />
    <div class="row">
        @foreach (Project project in Model.OrderBy(p => p.Name))
        {
            <div class="col-sm-12 col-md-6 pt-2 pb-2">
                <div class="card" style="height:auto; width:auto">
                    <div class="card-body">
                        <h4 class="card-title">@project.Name</h4>
                        <p class="card-text">@project.Description</p>
                        <div class="row">
                            <div class="col">
                                <a asp-controller="Projects" asp-action="Details" asp-route-id="@project.Id" class="btn btn-primary">Details</a>

                                @{
                                    //bool isProjectPM = (await _projectService.GetProjectManagerAsync(project.Id))?.Id == btUser.Id;


                                    if (User.IsInRole(nameof(Roles.Admin)))
                                    {
                                        <a class="btn btn-primary" asp-controller="Projects" asp-action="Edit" asp-route-id="@project.Id">Edit</a>

                                        <a class="btn btn-primary" asp-controller="Projects" asp-action="AssignPm" asp-route-projectId="@project.Id">Assign PM</a>

                                        @if (project.Archived)
                                        {
                                            <a class="btn btn-success" asp-action="Restore" asp-controller="Projects" asp-route-id="@project.Id">Restore</a>
                                        }
                                        else
                                        {
                                            <a class="btn btn-danger" asp-controller="Projects" asp-action="Archive" asp-route-id="@project.Id">Archive</a>
                                        }
                                    }
                                }
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        }
    </div>
</div>